apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-clusters
  namespace: kommander
spec:
  dependsOn:
    - name: clusterops-namespaces
    - name: clusterops-workspaces
  interval: 5s
  path: ./kustomizations/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander
