apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-namespaces
  namespace: kommander
spec:
  interval: 5s
  path: ./resources/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander
