apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-workspace-applications
  namespace: dm-nkp-gitops
spec:
  dependsOn:
    - name: clusterops-namespaces
      namespace: kommander
    - name: clusterops-workspaces
      namespace: dm-nkp-gitops
  interval: 5s
  path: ./kustomizations/workspaces/applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: kommander
