apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # DISABLED: kube-prometheus-stack
  # - kube-prometheus-stack
  # DISABLED: rook-ceph
  # - rook-ceph
  # DISABLED: rook-ceph-cluster
  # - rook-ceph-cluster

