apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/dm-nkp-workload-1.yaml
  - ../../bases/dm-nkp-workload-1-sealed-secrets.yaml
  - ../../bases/dm-nkp-workload-2.yaml
  - ../../bases/dm-nkp-workload-2-sealed-secrets.yaml

patches:
  - path: dm-nkp-workload-1-patch.yaml
  - path: dm-nkp-workload-2-patch.yaml
