apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # Note: CAPK components can be installed via clusterctl or the manifests below
  # Uncomment the following after generating manifests from clusterctl
  # - capk-components.yaml

