# Network Security Constraint Templates
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - block-nodeport.yaml
  - block-loadbalancer.yaml
  - require-ingress-tls.yaml
  - block-host-ports.yaml
  - validate-external-ports.yaml

